export const iso_3166_1_object = {
  "004": "AF:AFG:Afghanistan:Afghanistan (l')",
  "008": "AL:ALB:Albania:Albanie (l')",
  "012": "DZ:DZA:Algeria:Algérie (l')",
  "016": "AS:ASM:American Samoa:Samoa américaines (les)",
  "020": "AD:AND:Andorra:Andorre (l')",
  "024": "AO:AGO:Angola:Angola (l')",
  "010": "AQ:ATA:Antarctica:Antarctique (l')",
  "028": "AG:ATG:Antigua and Barbuda:Antigua-et-Barbuda",
  "032": "AR:ARG:Argentina:Argentine (l')",
  "051": "AM:ARM:Armenia:Arménie (l')",
  "036": "AU:AUS:Australia:Australie (l')",
  "040": "AT:AUT:Austria:Autriche (l')",
  "031": "AZ:AZE:Azerbaijan:Azerbaïdjan (l')",
  "044": "BS:BHS:Bahamas (the):Bahamas (les)",
  "048": "BH:BHR:Bahrain:Bahreïn",
  "050": "BD:BGD:Bangladesh:Bangladesh (le)",
  "052": "BB:BRB:Barbados:Barbade (la)",
  "056": "BE:BEL:Belgium:Belgique (la)",
  "084": "BZ:BLZ:Belize:Belize (le)",
  "060": "BM:BMU:Bermuda:Bermudes (les)",
  "064": "BT:BTN:Bhutan:Bhoutan (le)",
  "068":
    "BO:BOL:Bolivia (Plurinational State of):Bolivie (État plurinational de)",
  "070": "BA:BIH:Bosnia and Herzegovina:Bosnie-Herzégovine (la)",
  "072": "BW:BWA:Botswana:Botswana (le)",
  "074": "BV:BVT:Bouvet Island:Bouvet (l'Île)",
  "076": "BR:BRA:Brazil:Brésil (le)",
  "086":
    "IO:IOT:British Indian Ocean Territory (the):Indien (le&nbsp;Territoire britannique de l'océan)",
  "096": "BN:BRN:Brunei Darussalam:Brunéi Darussalam (le)",
  "090": "SB:SLB:Solomon Islands:Salomon (les Îles)",
  "092": "VG:VGB:Virgin Islands (British):Vierges britanniques (les&nbsp;Îles)",
  "100": "BG:BGR:Bulgaria:Bulgarie (la)",
  "104": "MM:MMR:Myanmar:Myanmar (le)",
  "108": "BI:BDI:Burundi:Burundi (le)",
  "112": "BY:BLR:Belarus:Bélarus (le)",
  "116": "KH:KHM:Cambodia:Cambodge (le)",
  "120": "CM:CMR:Cameroon:Cameroun (le)",
  "124": "CA:CAN:Canada:Canada (le)",
  "132": "CV:CPV:Cabo Verde:Cabo Verde",
  "136": "KY:CYM:Cayman Islands (the):Caïmans (les&nbsp;Îles)",
  "140": "CF:CAF:Central African Republic (the):République centrafricaine (la)",
  "144": "LK:LKA:Sri Lanka:Sri Lanka",
  "148": "TD:TCD:Chad:Tchad (le)",
  "152": "CL:CHL:Chile:Chili (le)",
  "156": "CN:CHN:China:Chine (la)",
  "158": "TW:TWN:Taiwan (Province of China):Taïwan (Province de Chine)",
  "162": "CX:CXR:Christmas Island:Christmas (l'Île)",
  "166":
    "CC:CCK:Cocos (Keeling) Islands (the):Cocos (les&nbsp;Îles)/ Keeling (les&nbsp;Îles)",
  "170": "CO:COL:Colombia:Colombie (la)",
  "174": "KM:COM:Comoros (the):Comores (les)",
  "175": "YT:MYT:Mayotte:Mayotte",
  "178": "CG:COG:Congo (the):Congo (le)",
  "180":
    "CD:COD:Congo (the Democratic Republic of the):Congo (la République démocratique du)",
  "184": "CK:COK:Cook Islands (the):Cook (les Îles)",
  "188": "CR:CRI:Costa Rica:Costa Rica (le)",
  "191": "HR:HRV:Croatia:Croatie (la)",
  "192": "CU:CUB:Cuba:Cuba",
  "196": "CY:CYP:Cyprus:Chypre",
  "203": "CZ:CZE:Czechia:Tchéquie (la)",
  "204": "BJ:BEN:Benin:Bénin (le)",
  "208": "DK:DNK:Denmark:Danemark (le)",
  "212": "DM:DMA:Dominica:Dominique (la)",
  "214": "DO:DOM:Dominican Republic (the):dominicaine (la&nbsp;République)",
  "218": "EC:ECU:Ecuador:Équateur (l')",
  "222": "SV:SLV:El Salvador:El Salvador",
  "226": "GQ:GNQ:Equatorial Guinea:Guinée équatoriale (la)",
  "231": "ET:ETH:Ethiopia:Éthiopie (l')",
  "232": "ER:ERI:Eritrea:Érythrée (l')",
  "233": "EE:EST:Estonia:Estonie (l')",
  "234": "FO:FRO:Faroe Islands (the):Féroé (les Îles)",
  "238":
    "FK:FLK:Falkland Islands (the) [Malvinas]:Falkland (les Îles)/Malouines (les Îles)",
  "239":
    "GS:SGS:South Georgia and the South Sandwich Islands:Géorgie du Sud-et-les Îles Sandwich du Sud (la)",
  "242": "FJ:FJI:Fiji:Fidji (les)",
  "246": "FI:FIN:Finland:Finlande (la)",
  "248": "AX:ALA:Åland Islands:Åland(les Îles)",
  "250": "FR:FRA:France:France (la)",
  "254": "GF:GUF:French Guiana:Guyane française (la&nbsp;)",
  "258": "PF:PYF:French Polynesia:Polynésie française (la)",
  "260":
    "TF:ATF:French Southern Territories (the):Terres australes françaises (les)",
  "262": "DJ:DJI:Djibouti:Djibouti",
  "266": "GA:GAB:Gabon:Gabon (le)",
  "268": "GE:GEO:Georgia:Géorgie (la)",
  "270": "GM:GMB:Gambia (the):Gambie (la)",
  "275": "PS:PSE:Palestine, State of:Palestine, État de",
  "276": "DE:DEU:Germany:Allemagne (l')",
  "288": "GH:GHA:Ghana:Ghana (le)",
  "292": "GI:GIB:Gibraltar:Gibraltar",
  "296": "KI:KIR:Kiribati:Kiribati",
  "300": "GR:GRC:Greece:Grèce (la)",
  "304": "GL:GRL:Greenland:Groenland (le)",
  "308": "GD:GRD:Grenada:Grenade (la)",
  "312": "GP:GLP:Guadeloupe:Guadeloupe (la)",
  "316": "GU:GUM:Guam:Guam",
  "320": "GT:GTM:Guatemala:Guatemala (le)",
  "324": "GN:GIN:Guinea:Guinée (la)",
  "328": "GY:GUY:Guyana:Guyana (le)",
  "332": "HT:HTI:Haiti:Haïti",
  "334":
    "HM:HMD:Heard Island and McDonald Islands:Heard-et-Îles MacDonald (l'Île)",
  "336": "VA:VAT:Holy See (the):Saint-Siège (le)",
  "340": "HN:HND:Honduras:Honduras (le)",
  "344": "HK:HKG:Hong Kong:Hong Kong",
  "348": "HU:HUN:Hungary:Hongrie (la)",
  "352": "IS:ISL:Iceland:Islande (l')",
  "356": "IN:IND:India:Inde (l')",
  "360": "ID:IDN:Indonesia:Indonésie (l')",
  "364": "IR:IRN:Iran (Islamic Republic of):Iran (République Islamique d')",
  "368": "IQ:IRQ:Iraq:Iraq (l')",
  "372": "IE:IRL:Ireland:Irlande (l')",
  "376": "IL:ISR:Israel:Israël",
  "380": "IT:ITA:Italy:Italie (l')",
  "383": "XK:XKX:Kosovo:Kosovo (le)",
  "384": "CI:CIV:Côte d'Ivoire:Côte d'Ivoire (la)",
  "388": "JM:JAM:Jamaica:Jamaïque (la)",
  "392": "JP:JPN:Japan:Japon (le)",
  "398": "KZ:KAZ:Kazakhstan:Kazakhstan (le)",
  "400": "JO:JOR:Jordan:Jordanie (la)",
  "404": "KE:KEN:Kenya:Kenya (le)",
  "408":
    "KP:PRK:Korea (the Democratic People's Republic of):Corée (la&nbsp;République populaire démocratique de)",
  "410": "KR:KOR:Korea (the Republic of):Corée (la République de)",
  "414": "KW:KWT:Kuwait:Koweït (le)",
  "417": "KG:KGZ:Kyrgyzstan:Kirghizistan (le)",
  "418":
    "LA:LAO:Lao People's Democratic Republic (the):Lao (la République démocratique populaire)",
  "422": "LB:LBN:Lebanon:Liban (le)",
  "426": "LS:LSO:Lesotho:Lesotho (le)",
  "428": "LV:LVA:Latvia:Lettonie (la)",
  "430": "LR:LBR:Liberia:Libéria (le)",
  "434": "LY:LBY:Libya:Libye (la)",
  "438": "LI:LIE:Liechtenstein:Liechtenstein (le)",
  "440": "LT:LTU:Lithuania:Lituanie (la)",
  "442": "LU:LUX:Luxembourg:Luxembourg (le)",
  "446": "MO:MAC:Macao:Macao",
  "450": "MG:MDG:Madagascar:Madagascar",
  "454": "MW:MWI:Malawi:Malawi (le)",
  "458": "MY:MYS:Malaysia:Malaisie (la)",
  "462": "MV:MDV:Maldives:Maldives (les)",
  "466": "ML:MLI:Mali:Mali (le)",
  "470": "MT:MLT:Malta:Malte",
  "474": "MQ:MTQ:Martinique:Martinique (la)",
  "478": "MR:MRT:Mauritania:Mauritanie (la)",
  "480": "MU:MUS:Mauritius:Maurice",
  "484": "MX:MEX:Mexico:Mexique (le)",
  "492": "MC:MCO:Monaco:Monaco",
  "496": "MN:MNG:Mongolia:Mongolie (la)",
  "498": "MD:MDA:Moldova (the Republic of):Moldova (la République de)",
  "499": "ME:MNE:Montenegro:Monténégro (le)",
  "500": "MS:MSR:Montserrat:Montserrat",
  "504": "MA:MAR:Morocco:Maroc (le)",
  "508": "MZ:MOZ:Mozambique:Mozambique (le)",
  "512": "OM:OMN:Oman:Oman",
  "516": "NA:NAM:Namibia:Namibie (la)",
  "520": "NR:NRU:Nauru:Nauru",
  "524": "NP:NPL:Nepal:Népal (le)",
  "528": "NL:NLD:Netherlands (Kingdom of the):Pays-Bas (Royaume des)",
  "531": "CW:CUW:Curaçao:Curaçao",
  "533": "AW:ABW:Aruba:Aruba",
  "534": "SX:SXM:Sint Maarten (Dutch part):Saint-Martin (partie néerlandaise)",
  "535":
    "BQ:BES:Bonaire, Sint Eustatius and Saba:Bonaire, Saint-Eustache et Saba",
  "540": "NC:NCL:New Caledonia:Nouvelle-Calédonie (la)",
  "548": "VU:VUT:Vanuatu:Vanuatu (le)",
  "554": "NZ:NZL:New Zealand:Nouvelle-Zélande (la)",
  "558": "NI:NIC:Nicaragua:Nicaragua (le)",
  "562": "NE:NER:Niger (the):Niger (le)",
  "566": "NG:NGA:Nigeria:Nigéria (le)",
  "570": "NU:NIU:Niue:Niue",
  "574": "NF:NFK:Norfolk Island:Norfolk (l'Île)",
  "578": "NO:NOR:Norway:Norvège (la)",
  "580": "MP:MNP:Northern Mariana Islands (the):Mariannes du Nord (les Îles)",
  "581":
    "UM:UMI:United States Minor Outlying Islands (the):Îles mineures éloignées des États-Unis (les)",
  "583":
    "FM:FSM:Micronesia (Federated States of):Micronésie (États fédérés de)",
  "584": "MH:MHL:Marshall Islands (the):Marshall (les Îles)",
  "585": "PW:PLW:Palau:Palaos (les)",
  "586": "PK:PAK:Pakistan:Pakistan (le)",
  "591": "PA:PAN:Panama:Panama (le)",
  "598": "PG:PNG:Papua New Guinea:Papouasie-Nouvelle-Guinée (la)",
  "600": "PY:PRY:Paraguay:Paraguay (le)",
  "604": "PE:PER:Peru:Pérou (le)",
  "608": "PH:PHL:Philippines (the):Philippines (les)",
  "612": "PN:PCN:Pitcairn:Pitcairn",
  "616": "PL:POL:Poland:Pologne (la)",
  "620": "PT:PRT:Portugal:Portugal (le)",
  "624": "GW:GNB:Guinea-Bissau:Guinée-Bissau (la)",
  "626": "TL:TLS:Timor-Leste:Timor-Leste (le)",
  "630": "PR:PRI:Puerto Rico:Porto Rico",
  "634": "QA:QAT:Qatar:Qatar (le)",
  "638": "RE:REU:Réunion:Réunion (La)",
  "642": "RO:ROU:Romania:Roumanie (la)",
  "643": "RU:RUS:Russian Federation (the):Russie (la Fédération de)",
  "646": "RW:RWA:Rwanda:Rwanda (le)",
  "652": "BL:BLM:Saint Barthélemy:Saint-Barthélemy",
  "654":
    "SH:SHN:Saint Helena, Ascension and Tristan da Cunha:Sainte-Hélène, Ascension et Tristan da Cunha",
  "659": "KN:KNA:Saint Kitts and Nevis:Saint-Kitts-et-Nevis",
  "660": "AI:AIA:Anguilla:Anguilla",
  "662": "LC:LCA:Saint Lucia:Sainte-Lucie",
  "663": "MF:MAF:Saint Martin (French part):Saint-Martin (partie française)",
  "666": "PM:SPM:Saint Pierre and Miquelon:Saint-Pierre-et-Miquelon",
  "670":
    "VC:VCT:Saint Vincent and the Grenadines:Saint-Vincent-et-les Grenadines",
  "674": "SM:SMR:San Marino:Saint-Marin",
  "678": "ST:STP:Sao Tome and Principe:Sao Tomé-et-Principe",
  "682": "SA:SAU:Saudi Arabia:Arabie saoudite (l')",
  "686": "SN:SEN:Senegal:Sénégal (le)",
  "688": "RS:SRB:Serbia:Serbie (la)",
  "690": "SC:SYC:Seychelles:Seychelles (les)",
  "694": "SL:SLE:Sierra Leone:Sierra Leone (la)",
  "702": "SG:SGP:Singapore:Singapour",
  "703": "SK:SVK:Slovakia:Slovaquie (la)",
  "704": "VN:VNM:Viet Nam:Viet Nam (le)",
  "705": "SI:SVN:Slovenia:Slovénie (la)",
  "706": "SO:SOM:Somalia:Somalie (la)",
  "710": "ZA:ZAF:South Africa:Afrique du Sud (l')",
  "716": "ZW:ZWE:Zimbabwe:Zimbabwe (le)",
  "724": "ES:ESP:Spain:Espagne (l')",
  "728": "SS:SSD:South Sudan:Soudan du Sud (le)",
  "729": "SD:SDN:Sudan (the):Soudan (le)",
  "732": "EH:ESH:Western Sahara*:Sahara occidental (le)*",
  "740": "SR:SUR:Suriname:Suriname (le)",
  "744": "SJ:SJM:Svalbard and Jan Mayen:Svalbard et l'Île Jan Mayen (le)",
  "748": "SZ:SWZ:Eswatini:Eswatini (l')",
  "752": "SE:SWE:Sweden:Suède (la)",
  "756": "CH:CHE:Switzerland:Suisse (la)",
  "760": "SY:SYR:Syrian Arab Republic (the):République arabe syrienne (la)",
  "762": "TJ:TJK:Tajikistan:Tadjikistan (le)",
  "764": "TH:THA:Thailand:Thaïlande (la)",
  "768": "TG:TGO:Togo:Togo (le)",
  "772": "TK:TKL:Tokelau:Tokelau (les)",
  "776": "TO:TON:Tonga:Tonga (les)",
  "780": "TT:TTO:Trinidad and Tobago:Trinité-et-Tobago (la)",
  "784": "AE:ARE:United Arab Emirates (the):Émirats arabes unis (les)",
  "788": "TN:TUN:Tunisia:Tunisie (la)",
  "792": "TR:TUR:Türkiye:Türkiye (la)",
  "795": "TM:TKM:Turkmenistan:Turkménistan (le)",
  "796": "TC:TCA:Turks and Caicos Islands (the):Turks-et-Caïcos (les Îles)",
  "798": "TV:TUV:Tuvalu:Tuvalu (les)",
  "800": "UG:UGA:Uganda:Ouganda (l')",
  "804": "UA:UKR:Ukraine:Ukraine (l')",
  "807": "MK:MKD:North Macedonia:Macédoine du Nord (la)",
  "818": "EG:EGY:Egypt:Égypte (l')",
  "826":
    "GB:GBR:United Kingdom of Great Britain and Northern Ireland (the):Royaume-Uni de Grande-Bretagne et d'Irlande du Nord (le)",
  "831": "GG:GGY:Guernsey:Guernesey",
  "832": "JE:JEY:Jersey:Jersey",
  "833": "IM:IMN:Isle of Man:Île de Man",
  "834":
    "TZ:TZA:Tanzania, the United Republic of:Tanzanie (la République-Unie de)",
  "840": "US:USA:United States of America (the):États-Unis d'Amérique (les)",
  "850": "VI:VIR:Virgin Islands (U.S.):Vierges des États-Unis (les Îles)",
  "854": "BF:BFA:Burkina Faso:Burkina Faso (le)",
  "858": "UY:URY:Uruguay:Uruguay (l')",
  "860": "UZ:UZB:Uzbekistan:Ouzbékistan (l')",
  "862":
    "VE:VEN:Venezuela (Bolivarian Republic of):Venezuela (République bolivarienne du)",
  "876": "WF:WLF:Wallis and Futuna:Wallis-et-Futuna",
  "882": "WS:WSM:Samoa:Samoa (le)",
  "887": "YE:YEM:Yemen:Yémen (le)",
  "894": "ZM:ZMB:Zambia:Zambie (la)"
};
