import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "./provider";
import "./globals.css";
import { default as SideBar } from "@/components/side-bar";
import { default as Hydration } from "./hydration";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Knightly",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <body className={inter.className}>
        <Providers>
          <Hydration />
          <SideBar />
          <main className="md:ml-18 ml-9 lg:ml-36">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
