"use client";

import { Calendar, MapPin } from "lucide-react";
import { motion } from "motion/react";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle
} from "@/ui/atoms/cards";

const experiences = [
  {
    title: "JAMstack Development Lead",
    company: "Takeda Pharmaceuticals",
    location: "Lexington, MA (Remote)",
    period: "April 2022 – September 2024",
    description:
      "Led a cross-functional team of developers from around the globe responsible for maintaining existing software and building out new solutions and experiences, Collaborated with other teams to successfully deploy the new Takeda dot com site across 70 geographies. Worked closely with the Immersive Experience team as their go-to engineer.",
    achievements: [
      "Decreased build times by 4x after persuading business unit to migrate from Netlify to Vercel; this increased developer efficiency and enhanced developer experience",
      "Developed an internal package ecosystem used by 20+ projects across the organization, significantly reducing code duplication and maintenance overhead",
      "Collaborated with the XR team to architect performant immersive experiences, showcasing Next.js and Vercel's potential in cutting-edge enterprise solutions at scale",
      "Guided the organization in adopting Next.js, coaching non-technical stakeholders on best practices and accelerating enterprise-wide buy-in",
      "Conducted several dozen interviews for Senior Engineer and Senior Architect roles and directly onboarded and mentored a handful of these hires",
      "Wrote a cli-based package to handle the transformation, optimization, and standardization of web assets generated by 3d software used to build virtual experiences (3dvista pro); currently all 20+ XR projects in production are powered by this package"
    ]
  },
  {
    title: "Software Engineer & HIPAA Compliance Officer",
    company: "Cortina",
    location: "Chattanooga, TN (Remote)",
    period: "May 2021 – February 2022",
    description:
      "Implemented a containerized Redis + Prisma + Node + Next stack that supported real-time data syncing and telemedicine compliance checks. Built integrations with Zendesk, HubSpot, and more.",
    achievements: [
      "Built an event-driven ticketing system for Patients/MDs",
      "Completed necessary steps to receive HIPAA seal of Compliance for the teledermatology startup",
      "Conducted weekly meetings with an external marketing firm; worked closely with the head designer"
    ]
  },
  {
    title: "Cofounder & Tech Lead",
    company: "Windy City Devs LLC",
    location: "Highland Park, IL",
    period: "March 2020 – February 2022",
    description:
      "Spearheaded modernizing client web presence via b2b solutions, championing AWS headless WordPress hosting, Next.js for improved performance, scalability, and SEO, and Vercel for the headless site itself.",
    achievements: [
      "Architected Headless WP strategy; modernize client web presence in terms of performance, SEO, scalability, flexibility, and design",
      "Optimized accessibility features by integrating AWS Polly and Alexa text-to-voice."
    ]
  },
  {
    title: "Full-Stack Bootcamp TA",
    company: "Vanderbilt University",
    location: "Nashville, TN (Remote)",
    period: "September 2020 – March 2021",
    description:
      "Provided weekly 1:1 and group instruction, guiding students through the exploration of a plethora of full-stack technologies. Assisted students with several core full-stack projects around React, Node, PostgreSQL, GraphQL, and more.",
    achievements: [
      "Mentored a cohort of 40+ aspiring developers through hands-on projects"
    ]
  }
];

export function ResumeTimeline() {
  return (
    <div className="space-y-8">
      {experiences.map((experience, index) => (
        <motion.div
          key={index}
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: index * 0.1 }}>
          <Card>
            <CardHeader>
              <div className="flex flex-col gap-2 md:flex-row md:items-center md:justify-between">
                <div>
                  <CardTitle>{experience.title}</CardTitle>
                  <CardDescription className="mt-1 text-base">
                    {experience.company}
                  </CardDescription>
                </div>
                <div className="text-muted-foreground flex flex-col text-sm">
                  <div className="flex items-center gap-1">
                    <Calendar className="h-4 w-4" />
                    <span>{experience.period}</span>
                  </div>
                  <div className="mt-1 flex items-center gap-1">
                    <MapPin className="h-4 w-4" />
                    <span>{experience.location}</span>
                  </div>
                </div>
              </div>
            </CardHeader>
            <CardContent>
              <p className="mb-4">{experience.description}</p>
              <ul className="list-disc space-y-2 pl-5">
                {experience.achievements.map((achievement, i) => (
                  <motion.li
                    key={i}
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    transition={{ delay: 0.3 + i * 0.1 }}>
                    {achievement}
                  </motion.li>
                ))}
              </ul>
            </CardContent>
          </Card>
        </motion.div>
      ))}
    </div>
  );
}
