export const tupleTopoData = {
  "004": "AF:AFG:Afghanistan",
  "008": "AL:ALB:Albania",
  "010": "AQ:ATA:Antarctica",
  "012": "DZ:DZA:Algeria",
  "024": "AO:AGO:Angola",
  "031": "AZ:AZE:Azerbaijan",
  "032": "AR:ARG:Argentina",
  "036": "AU:AUS:Australia",
  "040": "AT:AUT:Austria",
  "044": "BS:BHS:Bahamas",
  "050": "BD:BGD:Bangladesh",
  "051": "AM:ARM:Armenia",
  "056": "BE:BEL:Belgium",
  "064": "BT:BTN:Bhutan",
  "068": "BO:BOL:Bolivia",
  "070": "BA:BIH:Bosnia and Herzegovina",
  "072": "BW:BWA:Botswana",
  "076": "BR:BRA:Brazil",
  "084": "BZ:BLZ:Belize",
  "090": "SB:SLB:Solomon Islands",
  "096": "BN:BRN:Brunei Darussalam",
  "100": "BG:BGR:Bulgaria",
  "104": "MM:MMR:Myanmar",
  "108": "BI:BDI:Burundi",
  "112": "BY:BLR:Belarus",
  "116": "KH:KHM:Cambodia",
  "120": "CM:CMR:Cameroon",
  "124": "CA:CAN:Canada",
  "140": "CF:CAF:Central African Republic",
  "144": "LK:LKA:Sri Lanka",
  "148": "TD:TCD:Chad",
  "152": "CL:CHL:Chile",
  "156": "CN:CHN:China",
  "158": "TW:TWN:Taiwan, Province of China",
  "170": "CO:COL:Colombia",
  "178": "CG:COG:Congo",
  "180": "CD:COD:Congo",
  "188": "CR:CRI:Costa Rica",
  "191": "HR:HRV:Croatia",
  "192": "CU:CUB:Cuba",
  "196": "CY:CYP:Cyprus",
  "203": "CZ:CZE:Czech Republic",
  "204": "BJ:BEN:Benin",
  "208": "DK:DNK:Denmark",
  "214": "DO:DOM:Dominican Republic",
  "218": "EC:ECU:Ecuador",
  "222": "SV:SLV:El Salvador",
  "226": "GQ:GNQ:Equatorial Guinea",
  "231": "ET:ETH:Ethiopia",
  "232": "ER:ERI:Eritrea",
  "233": "EE:EST:Estonia",
  "238": "FK:FLK:Falkland Islands",
  "242": "FJ:FJI:Fiji",
  "246": "FI:FIN:Finland",
  "250": "FR:FRA:France",
  "260": "TF:ATF:French Southern Territories",
  "262": "DJ:DJI:Djibouti",
  "266": "GA:GAB:Gabon",
  "268": "GE:GEO:Georgia",
  "270": "GM:GMB:Gambia",
  "275": "PS:PSE:State of Palestine",
  "276": "DE:DEU:Germany",
  "288": "GH:GHA:Ghana",
  "300": "GR:GRC:Greece",
  "304": "GL:GRL:Greenland",
  "320": "GT:GTM:Guatemala",
  "324": "GN:GIN:Guinea",
  "328": "GY:GUY:Guyana",
  "332": "HT:HTI:Haiti",
  "340": "HN:HND:Honduras",
  "348": "HU:HUN:Hungary",
  "352": "IS:ISL:Iceland",
  "356": "IN:IND:India",
  "360": "ID:IDN:Indonesia",
  "364": "IR:IRN:Islamic Republic of Iran",
  "368": "IQ:IRQ:Iraq",
  "372": "IE:IRL:Ireland",
  "376": "IL:ISR:Israel",
  "380": "IT:ITA:Italy",
  "384": "CI:CIV:Côte d'Ivoire",
  "388": "JM:JAM:Jamaica",
  "392": "JP:JPN:Japan",
  "398": "KZ:KAZ:Kazakhstan",
  "400": "JO:JOR:Jordan",
  "404": "KE:KEN:Kenya",
  "408": "KP:PRK:Democratic People's Republic of Korea",
  "410": "KR:KOR:Republic of Korea",
  "414": "KW:KWT:Kuwait",
  "417": "KG:KGZ:Kyrgyzstan",
  "418": "LA:LAO:Lao People's Democratic Republic",
  "422": "LB:LBN:Lebanon",
  "426": "LS:LSO:Lesotho",
  "428": "LV:LVA:Latvia",
  "430": "LR:LBR:Liberia",
  "434": "LY:LBY:Libya",
  "440": "LT:LTU:Lithuania",
  "442": "LU:LUX:Luxembourg",
  "450": "MG:MDG:Madagascar",
  "454": "MW:MWI:Malawi",
  "458": "MY:MYS:Malaysia",
  "466": "ML:MLI:Mali",
  "478": "MR:MRT:Mauritania",
  "484": "MX:MEX:Mexico",
  "496": "MN:MNG:Mongolia",
  "498": "MD:MDA:Republic of Moldova",
  "499": "ME:MNE:Montenegro",
  "504": "MA:MAR:Morocco",
  "508": "MZ:MOZ:Mozambique",
  "512": "OM:OMN:Oman",
  "516": "NA:NAM:Namibia",
  "524": "NP:NPL:Nepal",
  "528": "NL:NLD:Netherlands",
  "540": "NC:NCL:New Caledonia",
  "548": "VU:VUT:Vanuatu",
  "554": "NZ:NZL:New Zealand",
  "558": "NI:NIC:Nicaragua",
  "562": "NE:NER:Niger",
  "566": "NG:NGA:Nigeria",
  "578": "NO:NOR:Norway",
  "586": "PK:PAK:Pakistan",
  "591": "PA:PAN:Panama",
  "598": "PG:PNG:Papua New Guinea",
  "600": "PY:PRY:Paraguay",
  "604": "PE:PER:Peru",
  "608": "PH:PHL:Philippines",
  "616": "PL:POL:Poland",
  "620": "PT:PRT:Portugal",
  "624": "GW:GNB:Guinea-Bissau",
  "626": "TL:TLS:Timor-Leste",
  "630": "PR:PRI:Puerto Rico",
  "634": "QA:QAT:Qatar",
  "642": "RO:ROU:Romania",
  "643": "RU:RUS:Russian Federation",
  "646": "RW:RWA:Rwanda",
  "682": "SA:SAU:Saudi Arabia",
  "686": "SN:SEN:Senegal",
  "688": "RS:SRB:Serbia",
  "694": "SL:SLE:Sierra Leone",
  "703": "SK:SVK:Slovakia",
  "704": "VN:VNM:Viet Nam",
  "705": "SI:SVN:Slovenia",
  "706": "SO:SOM:Somalia",
  "710": "ZA:ZAF:South Africa",
  "716": "ZW:ZWE:Zimbabwe",
  "724": "ES:ESP:Spain",
  "728": "SS:SSD:South Sudan",
  "729": "SD:SDN:Sudan",
  "732": "EH:ESH:Western Sahara",
  "740": "SR:SUR:Suriname",
  "748": "SZ:SWZ:Swaziland",
  "752": "SE:SWE:Sweden",
  "756": "CH:CHE:Switzerland",
  "760": "SY:SYR:Syrian Arab Republic",
  "762": "TJ:TJK:Tajikistan",
  "764": "TH:THA:Thailand",
  "768": "TG:TGO:Togo",
  "780": "TT:TTO:Trinidad and Tobago",
  "784": "AE:ARE:United Arab Emirates",
  "788": "TN:TUN:Tunisia",
  "792": "TR:TUR:Turkey",
  "795": "TM:TKM:Turkmenistan",
  "800": "UG:UGA:Uganda",
  "804": "UA:UKR:Ukraine",
  "807": "MK:MKD:Macedonia",
  "818": "EG:EGY:Egypt",
  "826": "GB:GBR:United Kingdom of Great Britain and Northern Ireland",
  "834": "TZ:TZA:United Republic of Tanzania",
  "840": "US:USA:United States of America",
  "854": "BF:BFA:Burkina Faso",
  "858": "UY:URY:Uruguay",
  "860": "UZ:UZB:Uzbekistan",
  "862": "VE:VEN:Venezuela (Bolivarian Republic of)",
  "887": "YE:YEM:Yemen",
  "894": "ZM:ZMB:Zambia"
} as const;

export type InferSplitOutput<T> = T extends `${infer U}:${infer V}:${infer W}`
  ? [U, V, W]
  : T;

export function exciseColons<const T extends `${string}:${string}:${string}`>(
  str: T
): InferSplitOutput<T> {
  return str.split(/:/g) as InferSplitOutput<typeof str>;
}

export const getCountryData = <const T extends keyof typeof tupleTopoData>(
  target: T
) => exciseColons(tupleTopoData[target]);

getCountryData("894");
