export const tupleTopoData = {
  "100": "BG:BGR:Bulgaria:bg.svg",
  "104": "MM:MMR:Myanmar:mm.svg",
  "108": "BI:BDI:Burundi:bi.svg",
  "112": "BY:BLR:Belarus:by.svg",
  "116": "KH:KHM:Cambodia:kh.svg",
  "120": "CM:CMR:Cameroon:cm.svg",
  "124": "CA:CAN:Canada:ca.svg",
  "140": "CF:CAF:Central African Republic:cf.svg",
  "144": "LK:LKA:Sri Lanka:lk.svg",
  "148": "TD:TCD:Chad:td.svg",
  "152": "CL:CHL:Chile:cl.svg",
  "156": "CN:CHN:China:cn.svg",
  "158": "TW:TWN:Taiwan, Province of China:tw.svg",
  "170": "CO:COL:Colombia:co.svg",
  "178": "CG:COG:Congo:cg.svg",
  "180": "CD:COD:Congo:cd.svg",
  "188": "CR:CRI:Costa Rica:cr.svg",
  "191": "HR:HRV:Croatia:hr.svg",
  "192": "CU:CUB:Cuba:cu.svg",
  "196": "CY:CYP:Cyprus:cy.svg",
  "203": "CZ:CZE:Czech Republic:cz.svg",
  "204": "BJ:BEN:Benin:bj.svg",
  "208": "DK:DNK:Denmark:dk.svg",
  "214": "DO:DOM:Dominican Republic:do.svg",
  "218": "EC:ECU:Ecuador:ec.svg",
  "222": "SV:SLV:El Salvador:sv.svg",
  "226": "GQ:GNQ:Equatorial Guinea:gq.svg",
  "231": "ET:ETH:Ethiopia:et.svg",
  "232": "ER:ERI:Eritrea:er.svg",
  "233": "EE:EST:Estonia:ee.svg",
  "238": "FK:FLK:Falkland Islands:fk.svg",
  "242": "FJ:FJI:Fiji:fj.svg",
  "246": "FI:FIN:Finland:fi.svg",
  "250": "FR:FRA:France:fr.svg",
  "260": "TF:ATF:French Southern Territories:tf.svg",
  "262": "DJ:DJI:Djibouti:dj.svg",
  "266": "GA:GAB:Gabon:ga.svg",
  "268": "GE:GEO:Georgia:ge.svg",
  "270": "GM:GMB:Gambia:gm.svg",
  "275": "PS:PSE:State of Palestine:ps.svg",
  "276": "DE:DEU:Germany:de.svg",
  "288": "GH:GHA:Ghana:gh.svg",
  "300": "GR:GRC:Greece:gr.svg",
  "304": "GL:GRL:Greenland:gl.svg",
  "320": "GT:GTM:Guatemala:gt.svg",
  "324": "GN:GIN:Guinea:gn.svg",
  "328": "GY:GUY:Guyana:gy.svg",
  "332": "HT:HTI:Haiti:ht.svg",
  "340": "HN:HND:Honduras:hn.svg",
  "348": "HU:HUN:Hungary:hu.svg",
  "352": "IS:ISL:Iceland:is.svg",
  "356": "IN:IND:India:in.svg",
  "360": "ID:IDN:Indonesia:id.svg",
  "364": "IR:IRN:Islamic Republic of Iran:ir.svg",
  "368": "IQ:IRQ:Iraq:iq.svg",
  "372": "IE:IRL:Ireland:ie.svg",
  "376": "IL:ISR:Israel:il.svg",
  "380": "IT:ITA:Italy:it.svg",
  "384": "CI:CIV:Côte d'Ivoire:ci.svg",
  "388": "JM:JAM:Jamaica:jm.svg",
  "392": "JP:JPN:Japan:jp.svg",
  "398": "KZ:KAZ:Kazakhstan:kz.svg",
  "400": "JO:JOR:Jordan:jo.svg",
  "404": "KE:KEN:Kenya:ke.svg",
  "408": "KP:PRK:Democratic People's Republic of Korea:kp.svg",
  "410": "KR:KOR:Republic of Korea:kr.svg",
  "414": "KW:KWT:Kuwait:kw.svg",
  "417": "KG:KGZ:Kyrgyzstan:kg.svg",
  "418": "LA:LAO:Lao People's Democratic Republic:la.svg",
  "422": "LB:LBN:Lebanon:lb.svg",
  "426": "LS:LSO:Lesotho:ls.svg",
  "428": "LV:LVA:Latvia:lv.svg",
  "430": "LR:LBR:Liberia:lr.svg",
  "434": "LY:LBY:Libya:ly.svg",
  "440": "LT:LTU:Lithuania:lt.svg",
  "442": "LU:LUX:Luxembourg:lu.svg",
  "450": "MG:MDG:Madagascar:mg.svg",
  "454": "MW:MWI:Malawi:mw.svg",
  "458": "MY:MYS:Malaysia:my.svg",
  "466": "ML:MLI:Mali:ml.svg",
  "478": "MR:MRT:Mauritania:mr.svg",
  "484": "MX:MEX:Mexico:mx.svg",
  "496": "MN:MNG:Mongolia:mn.svg",
  "498": "MD:MDA:Republic of Moldova:md.svg",
  "499": "ME:MNE:Montenegro:me.svg",
  "504": "MA:MAR:Morocco:ma.svg",
  "508": "MZ:MOZ:Mozambique:mz.svg",
  "512": "OM:OMN:Oman:om.svg",
  "516": "NA:NAM:Namibia:na.svg",
  "524": "NP:NPL:Nepal:np.svg",
  "528": "NL:NLD:Netherlands:nl.svg",
  "540": "NC:NCL:New Caledonia:nc.svg",
  "548": "VU:VUT:Vanuatu:vu.svg",
  "554": "NZ:NZL:New Zealand:nz.svg",
  "558": "NI:NIC:Nicaragua:ni.svg",
  "562": "NE:NER:Niger:ne.svg",
  "566": "NG:NGA:Nigeria:ng.svg",
  "578": "NO:NOR:Norway:no.svg",
  "586": "PK:PAK:Pakistan:pk.svg",
  "591": "PA:PAN:Panama:pa.svg",
  "598": "PG:PNG:Papua New Guinea:pg.svg",
  "600": "PY:PRY:Paraguay:py.svg",
  "604": "PE:PER:Peru:pe.svg",
  "608": "PH:PHL:Philippines:ph.svg",
  "616": "PL:POL:Poland:pl.svg",
  "620": "PT:PRT:Portugal:pt.svg",
  "624": "GW:GNB:Guinea-Bissau:gw.svg",
  "626": "TL:TLS:Timor-Leste:tl.svg",
  "630": "PR:PRI:Puerto Rico:pr.svg",
  "634": "QA:QAT:Qatar:qa.svg",
  "642": "RO:ROU:Romania:ro.svg",
  "643": "RU:RUS:Russian Federation:ru.svg",
  "646": "RW:RWA:Rwanda:rw.svg",
  "682": "SA:SAU:Saudi Arabia:sa.svg",
  "686": "SN:SEN:Senegal:sn.svg",
  "688": "RS:SRB:Serbia:rs.svg",
  "694": "SL:SLE:Sierra Leone:sl.svg",
  "703": "SK:SVK:Slovakia:sk.svg",
  "704": "VN:VNM:Viet Nam:vn.svg",
  "705": "SI:SVN:Slovenia:si.svg",
  "706": "SO:SOM:Somalia:so.svg",
  "710": "ZA:ZAF:South Africa:za.svg",
  "716": "ZW:ZWE:Zimbabwe:zw.svg",
  "724": "ES:ESP:Spain:es.svg",
  "728": "SS:SSD:South Sudan:ss.svg",
  "729": "SD:SDN:Sudan:sd.svg",
  "732": "EH:ESH:Western Sahara:eh.svg",
  "740": "SR:SUR:Suriname:sr.svg",
  "748": "SZ:SWZ:Swaziland:sz.svg",
  "752": "SE:SWE:Sweden:se.svg",
  "756": "CH:CHE:Switzerland:ch.svg",
  "760": "SY:SYR:Syrian Arab Republic:sy.svg",
  "762": "TJ:TJK:Tajikistan:tj.svg",
  "764": "TH:THA:Thailand:th.svg",
  "768": "TG:TGO:Togo:tg.svg",
  "780": "TT:TTO:Trinidad and Tobago:tt.svg",
  "784": "AE:ARE:United Arab Emirates:ae.svg",
  "788": "TN:TUN:Tunisia:tn.svg",
  "792": "TR:TUR:Turkey:tr.svg",
  "795": "TM:TKM:Turkmenistan:tm.svg",
  "800": "UG:UGA:Uganda:ug.svg",
  "804": "UA:UKR:Ukraine:ua.svg",
  "807": "MK:MKD:Macedonia:mk.svg",
  "818": "EG:EGY:Egypt:eg.svg",
  "826": "GB:GBR:United Kingdom of Great Britain and Northern Ireland:gb.svg",
  "834": "TZ:TZA:United Republic of Tanzania:tz.svg",
  "840": "US:USA:United States of America:us.svg",
  "854": "BF:BFA:Burkina Faso:bf.svg",
  "858": "UY:URY:Uruguay:uy.svg",
  "860": "UZ:UZB:Uzbekistan:uz.svg",
  "862": "VE:VEN:Venezuela (Bolivarian Republic of):ve.svg",
  "887": "YE:YEM:Yemen:ye.svg",
  "894": "ZM:ZMB:Zambia:zm.svg",
  "004": "AF:AFG:Afghanistan:af.svg",
  "008": "AL:ALB:Albania:al.svg",
  "010": "AQ:ATA:Antarctica:aq.svg",
  "012": "DZ:DZA:Algeria:dz.svg",
  "024": "AO:AGO:Angola:ao.svg",
  "031": "AZ:AZE:Azerbaijan:az.svg",
  "032": "AR:ARG:Argentina:ar.svg",
  "036": "AU:AUS:Australia:au.svg",
  "040": "AT:AUT:Austria:at.svg",
  "044": "BS:BHS:Bahamas:bs.svg",
  "050": "BD:BGD:Bangladesh:bd.svg",
  "051": "AM:ARM:Armenia:am.svg",
  "056": "BE:BEL:Belgium:be.svg",
  "064": "BT:BTN:Bhutan:bt.svg",
  "068": "BO:BOL:Bolivia:bo.svg",
  "070": "BA:BIH:Bosnia and Herzegovina:ba.svg",
  "072": "BW:BWA:Botswana:bw.svg",
  "076": "BR:BRA:Brazil:br.svg",
  "084": "BZ:BLZ:Belize:bz.svg",
  "090": "SB:SLB:Solomon Islands:sb.svg",
  "096": "BN:BRN:Brunei Darussalam:bn.svg"
};